"""
reports.py - PDF / Excel report generation.
PDF is implemented with fpdf2. Excel is a scaffolded CSV export (XLSX deferred).
"""
import csv
import io
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

import domain
from repository import OUTPUTS_DIR
from schemas import DetectionOut, ReportSummary

APP_TITLE = "Oyster Mushroom Disease Detection System"

# palette (matches the app theme)
PRIMARY = (62, 93, 70)
TEXT = (46, 46, 46)
MUTED = (120, 120, 120)
COLOR = {
    domain.HEALTHY: (90, 164, 105),
    domain.GREEN_MOLD: (245, 166, 35),
    domain.BLACK_MOLD: (155, 45, 45),
}


def _fmt(dt: Optional[datetime]) -> str:
    return dt.strftime("%b %d, %Y, %I:%M %p") if dt else "-"


class _Report(FPDF):
    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, self.w, 22, style="F")
        self.set_xy(10, 6)
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "Oyster Disease Report", align="L")
        self.ln(20)
        self.set_text_color(*TEXT)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 10, f"Generated by {APP_TITLE}", align="C")


def _row(pdf: _Report, label: str, value: str):
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*MUTED)
    pdf.cell(45, 8, label)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*TEXT)
    pdf.multi_cell(0, 8, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def build_single_pdf(det: DetectionOut) -> bytes:
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*PRIMARY)
    pdf.cell(0, 10, f"Report #{det.id:05d}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # captured image (annotated)
    if det.image:
        img_path = OUTPUTS_DIR / det.image
        if img_path.exists():
            try:
                pdf.image(str(img_path), w=110)
                pdf.ln(4)
            except Exception:
                pass

    # status chip
    c = COLOR.get(det.prediction, MUTED)
    pdf.set_fill_color(*c)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 12)
    label = det.disease_display + (f" ({det.scientific_name})" if det.scientific_name else "")
    pdf.cell(0, 10, f"  {label}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.set_text_color(*TEXT)
    pdf.ln(4)

    _row(pdf, "Rack ID", det.rack_name)
    _row(pdf, "Bag ID", det.bag_id)
    _row(pdf, "Prediction", det.disease_display)
    _row(pdf, "Confidence", f"{det.confidence * 100:.1f}%")
    _row(pdf, "Detection Time", _fmt(det.captured_at))
    if det.inference_time_ms is not None:
        _row(pdf, "Inference Time", f"{det.inference_time_ms:.0f} ms")
    if det.notes:
        _row(pdf, "Notes", det.notes)
    pdf.ln(2)
    _row(pdf, "Recommendation", det.recommendation)

    return bytes(pdf.output())


def build_summary_pdf(summary: ReportSummary, items: List[DetectionOut]) -> bytes:
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*PRIMARY)
    pdf.cell(0, 10, "Summary Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 6, f"Generated {_fmt(datetime.utcnow())} UTC", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    stats = [
        ("Total Detections", summary.total),
        ("Contaminated Cases", summary.contaminated),
        ("Healthy Cases", summary.healthy),
        ("Green Mold", summary.green_mold),
        ("Black Mold", summary.black_mold),
    ]
    for label, val in stats:
        _row(pdf, label, str(val))
    pdf.ln(4)

    # recent records table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*PRIMARY)
    pdf.cell(0, 8, "Recent Detections", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(*PRIMARY)
    widths = [22, 22, 45, 30, 55]
    headers = ["Rack", "Bag", "Prediction", "Confidence", "Detected"]
    for w, h in zip(widths, headers):
        pdf.cell(w, 8, h, border=0, fill=True, align="L")
    pdf.ln(8)

    pdf.set_text_color(*TEXT)
    pdf.set_font("Helvetica", "", 9)
    for i, det in enumerate(items[:40]):
        if i % 2 == 0:
            pdf.set_fill_color(244, 246, 242)
            fill = True
        else:
            fill = False
        pdf.cell(widths[0], 7, det.rack_name, fill=fill)
        pdf.cell(widths[1], 7, det.bag_id, fill=fill)
        pdf.cell(widths[2], 7, det.disease_display, fill=fill)
        pdf.cell(widths[3], 7, f"{det.confidence * 100:.0f}%", fill=fill)
        pdf.cell(widths[4], 7, _fmt(det.captured_at), fill=fill)
        pdf.ln(7)

    return bytes(pdf.output())


def build_csv(items: List[DetectionOut]) -> bytes:
    """Scaffolded Excel export -> CSV (full XLSX deferred)."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        ["ID", "Rack", "Bag", "Prediction", "Confidence", "Notes", "Detected At"]
    )
    for d in items:
        writer.writerow(
            [
                d.id,
                d.rack_name,
                d.bag_id,
                d.disease_display,
                f"{d.confidence:.4f}",
                d.notes or "",
                d.captured_at.isoformat(),
            ]
        )
    return buf.getvalue().encode("utf-8")
